disabled = false
languageCode = "zh_cn"
languageName = "简体中文"
weight = 1
title = "老王的冒险之旅"

[params]
  displayName = "简体中文"
  isoCode = "zh_cn"
  rtl = false
  dateFormat = "2 January 2006"
  # 亮色 Logo
  logo = "img/logo.png"
  # 暗色 Logo
  secondaryLogo = "img/secondary-logo.png"
  # 网站描述
  description = "My awesome website"
  # 版权声明
  #copyright = "Copy, _right?_ :thinking_face:"

# 作者
[params.author]
  # 名称
  name = "KingPrimes"
  # 头像 可以是Url
  image = "img/author.png"
  # 
  imageQuality = 96
  # 作者头衔
  headline = "I'm only human"
  # 简介
  bio = "A little bit about you"
  # 链接
  links = [
    { github = "https://github.com/KingPrimes" },
    { bilibili = "https://space.bilibili.com/16131052"},
  ]
