[[main]]
name = "帖子"
pageRef = "posts"
weight = 1

[[main]]
name = "文档"
pageRef = "docs"
weight = 2

[[main]]
name = "标签"
pageRef = "tags"
weight = 3

[[main]]
name = "分类"
pageRef = "categories"
weight = 4

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/KingPrimes"
weight = 400